# Generated by Django 2.2.5 on 2019-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('bloodgrp', models.CharField(choices=[('A+ve', 'A+ve'), ('A-ve', 'A-ve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('O-ve', 'O-ve'), ('O+ve', 'O+ve')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('aadharno', models.IntegerField(unique=True)),
                ('allergies', models.CharField(max_length=150)),
                ('alchohol', models.BooleanField()),
                ('diabetes', models.BooleanField(default=0)),
            ],
        ),
    ]
