# Generated by Django 2.2.6 on 2019-10-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alchohol',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cig',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imm',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='iname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='injuries',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='insdet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medinfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='polno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regmed',
            field=models.CharField(default='', max_length=200),
        ),
    ]
