# Generated by Django 2.2.6 on 2019-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_auto_20191031_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='injuries',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medinfo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='regmed',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
