# Generated by Django 2.2.5 on 2019-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes',
            field=models.BooleanField(),
        ),
    ]
