# Generated by Django 2.2.6 on 2019-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_auto_20191031_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pno',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aadharno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='eno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phyno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='polno',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
