# Generated by Django 2.2.6 on 2019-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_auto_20191031_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alchohol',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cig',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imm',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
