# Generated by Django 2.2.6 on 2019-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_auto_20191031_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alchohol',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.IntegerField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cig',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diabetes',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imm',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
