# Generated by Django 2.2.6 on 2019-10-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_auto_20191031_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
